import { SidebarProvider } from "@/context/SidebarContext";
import { AuthProvider } from "./Providers";
import "./globals.css";
import { Inter } from "next/font/google";
import GlobalState from "@/context";
import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <GlobalState>
            <SidebarProvider>
              <ToastContainer />
              {children}
            </SidebarProvider>
          </GlobalState>
        </AuthProvider>
      </body>
    </html>
  );
}
